default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://github.com/prettier/prettier
    rev: "1.19.1"
    hooks:
      - id: prettier
        # exclude: |
        #   (?x)
        #   # This file has wrong syntax and would fail
        #   ^tests/demo_invalid/copier.yml$
        #   ^tests/demo_config_transclude_multi/demo/copier.yml$
        exclude: |
          (?x)
          # This file has wrong syntax and would fail
          ^tests/demo_invalid/copier.yml|tests/demo_config_transclude_multi/demo/copier.yml$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        # Some tests require no EOF or they will fail
        exclude: \.noeof\.
      - id: debug-statements
      - id: flake8
        args: ["--config", "pyproject.toml"]
        additional_dependencies:
          - flake8-bugbear==19.8.0
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: mixed-line-ending
        args: ["--fix=lf"]
