# Defaults for all prettier-supported languages
bracketSpacing: false
endOfLine: lf
printWidth: 88
tabWidth: 4

# Language-specific
overrides:
  - files:
      - "*.json"
      - "*.yaml"
      - "*.yml"
    options:
      tabWidth: 2
