dist: bionic
language: python
python:

matrix:
  allow_failures:
    - python: "nightly"

before_install:
  - pip install -U pip coveralls

install:
  - pip install .[testing]
  - pre-commit install-hooks

script:
  - pre-commit run --all-files
  - pytest --cov copier copier tests

after_success:
  - coveralls
