dist: bionic
language: python
python:

cache:
  directories:
    - $HOME/.cache/pip
    # Add cache for pre-commit on repo that uses it (mandatory for >= 13)
    - $HOME/.cache/pre-commit

matrix:
  allow_failures:
    - python: 'nightly'

before_install:
  - pip install -U pip coveralls

install:
  - pip install .[testing]

script:
  - pre-commit run --all-files
  - pytest --cov copier copier tests

after_success:
  - coveralls
