[build-system]
requires = ["setuptools>=34.4", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
# See https://github.com/psf/black
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["colorama", "jinja2", "pkg_resources", "plumbum", "pydantic", "pytest", "ruamel", "setuptools", "six"]
line_length = 88
multi_line_output = 3
use_parentheses = true
